name: Prepare Release Draft

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  draft:
    name: Create Draft Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          draft: true
          generate_release_notes: true
